services:
  postgres:
    image: postgres:15
    container_name: magic-forge-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forgedb
    ports:
      - "5432:5432"