spring:
  # configurazione SQLite
  datasource:
    url: jdbc:sqlite:rider-dispatch.db
    driver-class-name: org.sqlite.JDBC

  # configurazione Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.add.type.headers]": false

    consumer:
      group-id: rider-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.value.default.type]": "it.exprivia.rider_dispatch.model.dto.RiderDTO"
        "[spring.json.trusted.packages]": "*"